name: Deploy site

on:
  workflow_run:
    workflows: ["Build site"]
    branches: [master]
    types: [completed]
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the user that starts the workflow'
        required: true
        default: 'Paolo Salvatori'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env: 
      STORAGE_ACCOUNT_NAME: baboweb
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build-site.yml
        workflow_conclusion: success
    
    - name: Azure login
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Upload to Azure blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.32.00
        inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ env.STORAGE_ACCOUNT_NAME }} \
              --destination '$web' \
              --source ./production-files
    
    - name: Azure logout
      run: |
            az logout
