name: Deploy site

on:
  workflow_run:
    workflows: ["Build site"]
    branches: [master]
    types: [completed]
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the user that starts the workflow'
        required: true
        default: 'Paolo Salvatori'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env: 
      STORAGE_ACCOUNT_NAME: baboweb
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build-site.yml
        workflow_conclusion: success
    
    - name: Azure login
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Upload to Azure blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.32.0
        inlineScript: |
          echo "Retrieving the primary key of the [${{ env.STORAGE_ACCOUNT_NAME }}] storage account..."
          storageAccountKey=$(az storage account keys list --resource-group $resourceGroupName --account-name ${{ env.STORAGE_ACCOUNT_NAME }} --query [0].value -o tsv)

          if [[ -n $storageAccountKey ]]; then
            echo "Primary key of the [${{ env.STORAGE_ACCOUNT_NAME }}] storage account successfully retrieved"
          else
            echo "Failed to retrieve the primary key of the [${{ env.STORAGE_ACCOUNT_NAME }}] storage account"
            exit
          fi

          echo "Uploading files to [${{ env.STORAGE_ACCOUNT_NAME }}] storage account..."
          az storage blob upload-batch \
              --account-name ${{ env.STORAGE_ACCOUNT_NAME }} \
              --destination '$web' \
              --source ./production-files
          
          if [[ $? == 0 ]]; then
            echo "Files successfully uploaded to the [$storageAccountName] storage account"
          else
            echo "Failed to upload files to the [$storageAccountName] storage account"
            exit
          fi
    
    - name: Azure logout
      run: |
            az logout
